# 异常处理
在 C++ 中，程序的异常处理是一种非常重要的机制，能够帮助程序员更好地处理运行时产生的错误。异常处理机制是将程序中可能出现的错误情况进行抛出、捕获、处理等操作，从而能够让程序更具有健壮性。

## 抛出异常
当程序运行到了某一处不可处理的错误状态时，不仅仅只停留在出错的地方，而是会将错误状态抛出，从而让其他能够处理这种错误的代码来处理这个错误状态。C++ 中使用 throw 来抛出异常，其具体语法与使用方法如下：
```cpp
throw exception_type();
```

其中， exception_type 是异常类型，可以是内置数据类型也可以是自定义数据类型。在 throw 抛出了异常之后，其它代码需要进行异常捕获和处理。

捕获异常
C++ 中的异常处理机制使用 try...catch 结构来捕获异常。其中，try 代码块是用来包裹可能抛出异常的代码块。当这个代码块中的代码抛出了异常，其对应的 catch 代码块就会被执行。catch 所引用的异常类型必须与 throw 所抛出的异常类型一致，才能正确捕获并处理异常。

下面是一个异常处理的示例代码：
```cpp
#include <iostream>
using namespace std;

int main() {
  try {
    // 抛出异常
    throw 100;
  } catch (int e) {
    // 捕获异常并处理
    cout << "An exception occurred. Exception Number: " << e << endl;
  }

  return 0;
}
```

在上述代码中，我们使用了 throw 来抛出了一个整型异常，然后使用了 try...catch 对其进行了捕获和处理。

## 自定义异常
在实际应用中，我们往往会创建自定义类型的异常，以便能够更好地处理具体的异常情况。在 C++ 中，我们可以通过继承 exception 类来自定义异常。具体操作如下：
```cpp
#include <iostream>
#include <exception>
using namespace std;

class MyException: public exception {
public:
  const char* what() const throw() {
    return "C++ Exception";
  }
};

int main() {
  try {
    throw MyException();
  } catch(MyException& e) {
    cout << "MyException caught: " << e.what() << endl;
  } catch(exception& e) {
    cout << "Other exception caught: " << e.what() << endl;
  }

  return 0;
}
```

在上述代码中，我们定义了一个自定义异常 MyException，并继承了内置的 exception 类。通过 what() 成员函数来返回异常的描述信息。这个机制使我们可以根据需要自定义异常类型，从而让程序更具有可读性和可维护性。

## 注意事项
在使用异常处理机制时需要注意以下几点：

1. 尽量避免过多的使用异常处理，因为异常处理会对程序的性能产生一定的影响，尤其是对于实时性要求比较高的程序。
2. 应该尽量使用内置的异常类型，不要过多自定义异常类型，以减少学习和维护成本。
3. 在抛出异常时，应该准确、明确地指定异常类型，以便在异常处理模块中能够准确处理。
4. 应该尽可能将异常处理写在合适的位置，以最大程度地保证程序的健壮性和稳定性。